### PR TITLE
Rewrite grammar

### PR DESCRIPTION
**Pull request by Alhadis**
You're welcome.

**Before:**
before

**After:**
after

### CODE REVIEW

**Comment by Alhadis** [comment]
@devoncarew Those screenshots give only a very modest overview of the improvements... you'd best examine them for yourself.

Assuming this gets merged, I'll arrange to have it provide syntax highlighting for `gn` files on GitHub. =)

**Comment by devoncarew** [comment]
👍 Thanks! I do plan to review, I'm just a bit swamped right now.

**Comment by Alhadis** [comment]
**FYI:** Your grammar is now [providing GN highlighting](https://github.com/v8/v8/blob/f8cbe2768cc88cb40e24c929fb28965bfb0ca6fe/BUILD.gn) across GitHub. =)

([This](https://github-lightshow.herokuapp.com/?utf8=%E2%9C%93&scope=from-url&grammar_url=https%3A%2F%2Fgithub.com%2FAlhadis%2Flanguage-gn%2Fblob%2Ffixes%2Fgrammars%2Fgn.cson&grammar_text=&code_source=from-url&code_url=https%3A%2F%2Fgithub.com%2Fv8%2Fv8%2Fblob%2Ff8cbe2768cc88cb40e24c929fb28965bfb0ca6fe%2FBUILD.gn&code=) might help your review, BTW).

**Comment by devoncarew** [comment]
> FYI: Your grammar is now providing GN highlighting across GitHub. =)

Well that's cool :)

I hadn't really planned to do that much with this plugin, and it now seems like you've done a fair amount of work. Any interest in taking this repo over?

**Comment by Alhadis** [comment]
I'd be happy to. =)

**Comment by Alhadis** [comment]
You'll also need to cut a new release before the changes can be delivered to users, BTW.

**Pull request merged**
